#!/usr/bin/env bash
echo "put-object"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

#https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html



# Check for file name prefix 
if [ -z "$2" ]; then
    echo "There needs to be a filename eg. ./bucket my-bucket-name my-filename"
    exit 2
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY